var $intern_59 = '102', $intern_57 = '110px', $intern_56 = '460px';
function com_google_gwt_storage_client_StorageImplNonNativeEvents_$setItem__Lcom_google_gwt_storage_client_StorageImplNonNativeEvents_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2V(storage, key, data){
  $wnd[storage].getItem(key);
  $wnd[storage].setItem(key, data);
}

function com_google_gwt_user_client_ui_HorizontalPanel_$add__Lcom_google_gwt_user_client_ui_HorizontalPanel_2Lcom_google_gwt_user_client_ui_Widget_2V(this$static, w){
  var td, com_google_gwt_user_client_ui_HorizontalPanel_$createAlignedTd__Lcom_google_gwt_user_client_ui_HorizontalPanel_2Lcom_google_gwt_user_client_Element_2_td_0;
  td = (com_google_gwt_user_client_ui_HorizontalPanel_$createAlignedTd__Lcom_google_gwt_user_client_ui_HorizontalPanel_2Lcom_google_gwt_user_client_Element_2_td_0 = $doc.createElement($intern_44) , com_google_gwt_user_client_ui_HorizontalPanel_$createAlignedTd__Lcom_google_gwt_user_client_ui_HorizontalPanel_2Lcom_google_gwt_user_client_Element_2_td_0[$intern_45] = this$static.com_google_gwt_user_client_ui_HorizontalPanel_horzAlign.com_google_gwt_user_client_ui_HasHorizontalAlignment$HorizontalAlignmentConstant_textAlignString , com_google_gwt_user_client_DOM_setStyleAttribute__Lcom_google_gwt_user_client_Element_2Ljava_lang_String_2Ljava_lang_String_2V(com_google_gwt_user_client_ui_HorizontalPanel_$createAlignedTd__Lcom_google_gwt_user_client_ui_HorizontalPanel_2Lcom_google_gwt_user_client_Element_2_td_0, $intern_46, this$static.com_google_gwt_user_client_ui_HorizontalPanel_vertAlign.com_google_gwt_user_client_ui_HasVerticalAlignment$VerticalAlignmentConstant_verticalAlignString) , com_google_gwt_user_client_ui_HorizontalPanel_$createAlignedTd__Lcom_google_gwt_user_client_ui_HorizontalPanel_2Lcom_google_gwt_user_client_Element_2_td_0);
  com_google_gwt_dom_client_Node_$appendChild__Lcom_google_gwt_dom_client_Node_2Lcom_google_gwt_dom_client_Node_2Lcom_google_gwt_dom_client_Node_2(this$static.com_google_gwt_user_client_ui_HorizontalPanel_tableRow, com_google_gwt_user_client_ui_PotentialElement_$resolve__Lcom_google_gwt_user_client_ui_PotentialElement_2Lcom_google_gwt_dom_client_Element_2(td));
  com_google_gwt_user_client_ui_ComplexPanel_$add__Lcom_google_gwt_user_client_ui_ComplexPanel_2Lcom_google_gwt_user_client_ui_Widget_2Lcom_google_gwt_user_client_Element_2V(this$static, w, td);
}

function com_google_gwt_user_client_ui_HorizontalPanel_$setHorizontalAlignment__Lcom_google_gwt_user_client_ui_HorizontalPanel_2Lcom_google_gwt_user_client_ui_HasHorizontalAlignment$HorizontalAlignmentConstant_2V(this$static, align){
  this$static.com_google_gwt_user_client_ui_HorizontalPanel_horzAlign = align;
}

function com_google_gwt_user_client_ui_HorizontalPanel_HorizontalPanel__V(){
  com_google_gwt_user_client_ui_CellPanel_CellPanel__V.call(this);
  this.com_google_gwt_user_client_ui_HorizontalPanel_horzAlign = (com_google_gwt_user_client_ui_HasHorizontalAlignment_$clinit__V() , com_google_gwt_user_client_ui_HasHorizontalAlignment_ALIGN_1DEFAULT);
  this.com_google_gwt_user_client_ui_HorizontalPanel_vertAlign = (com_google_gwt_user_client_ui_HasVerticalAlignment_$clinit__V() , com_google_gwt_user_client_ui_HasVerticalAlignment_ALIGN_1TOP);
  this.com_google_gwt_user_client_ui_HorizontalPanel_tableRow = $doc.createElement($intern_47);
  com_google_gwt_dom_client_Node_$appendChild__Lcom_google_gwt_dom_client_Node_2Lcom_google_gwt_dom_client_Node_2Lcom_google_gwt_dom_client_Node_2(this.com_google_gwt_user_client_ui_CellPanel_body, com_google_gwt_user_client_ui_PotentialElement_$resolve__Lcom_google_gwt_user_client_ui_PotentialElement_2Lcom_google_gwt_dom_client_Element_2(this.com_google_gwt_user_client_ui_HorizontalPanel_tableRow));
  this.com_google_gwt_user_client_ui_CellPanel_table[$intern_48] = $intern_49;
  this.com_google_gwt_user_client_ui_CellPanel_table[$intern_50] = $intern_49;
}

_ = com_google_gwt_user_client_ui_HorizontalPanel_HorizontalPanel__V.prototype = com_google_gwt_user_client_ui_HorizontalPanel.prototype;
_.remove__Lcom_google_gwt_user_client_ui_Widget_2Z = function com_google_gwt_user_client_ui_HorizontalPanel_remove__Lcom_google_gwt_user_client_ui_Widget_2Z(w){
  var removed, td;
  td = com_google_gwt_dom_client_DOMImpl_$getParentElement__Lcom_google_gwt_dom_client_DOMImpl_2Lcom_google_gwt_dom_client_Node_2Lcom_google_gwt_dom_client_Element_2(w.com_google_gwt_user_client_ui_UIObject_element);
  removed = com_google_gwt_user_client_ui_ComplexPanel_$remove__Lcom_google_gwt_user_client_ui_ComplexPanel_2Lcom_google_gwt_user_client_ui_Widget_2Z(this, w);
  removed && com_google_gwt_dom_client_Node_$removeChild__Lcom_google_gwt_dom_client_Node_2Lcom_google_gwt_dom_client_Node_2Lcom_google_gwt_dom_client_Node_2(this.com_google_gwt_user_client_ui_HorizontalPanel_tableRow, td);
  return removed;
}
;
function com_google_gwt_user_client_ui_LabelBase_$setHorizontalAlignment__Lcom_google_gwt_user_client_ui_LabelBase_2Lcom_google_gwt_user_client_ui_HasHorizontalAlignment$HorizontalAlignmentConstant_2V(this$static, align){
  this$static.com_google_gwt_user_client_ui_LabelBase_autoHorizontalAlignment = align;
  com_google_gwt_user_client_ui_LabelBase_$updateHorizontalAlignment__Lcom_google_gwt_user_client_ui_LabelBase_2V(this$static);
}

function com_google_gwt_user_client_ui_VerticalPanel_$setHorizontalAlignment__Lcom_google_gwt_user_client_ui_VerticalPanel_2Lcom_google_gwt_user_client_ui_HasHorizontalAlignment$HorizontalAlignmentConstant_2V(this$static, align){
  this$static.com_google_gwt_user_client_ui_VerticalPanel_horzAlign = align;
}

function pur_gwtplatform_samples_events_InsertCompleteEvent_$dispatch__Lpur_gwtplatform_samples_events_InsertCompleteEvent_2Lpur_gwtplatform_samples_events_InsertCompleteEvent$InsertCompleteHandler_2V(this$static, handler){
  java_util_ArrayList_$add__Ljava_util_ArrayList_2Ljava_lang_Object_2Z(handler.pur_gwtplatform_samples_presenter_MainPresenter$4_this$0.pur_gwtplatform_samples_presenter_MainPresenter_liste, new pur_gwtplatform_samples_model_Data_Data__Ljava_lang_String_2Ljava_lang_String_2V(this$static.pur_gwtplatform_samples_events_InsertCompleteEvent_data.pur_gwtplatform_samples_model_Data_id, this$static.pur_gwtplatform_samples_events_InsertCompleteEvent_data.pur_gwtplatform_samples_model_Data_value));
  com_google_gwt_user_cellview_client_AbstractHasData_$setRowData__Lcom_google_gwt_user_cellview_client_AbstractHasData_2Ljava_util_List_2V(handler.pur_gwtplatform_samples_presenter_MainPresenter$4_this$0.pur_gwtplatform_samples_presenter_MainPresenter_dataGrid, handler.pur_gwtplatform_samples_presenter_MainPresenter$4_this$0.pur_gwtplatform_samples_presenter_MainPresenter_liste);
}

function pur_gwtplatform_samples_events_InsertCompleteEvent_InsertCompleteEvent__Lpur_gwtplatform_samples_model_Data_2V(data){
  pur_gwtplatform_samples_events_InsertCompleteEvent_$clinit__V();
  this.pur_gwtplatform_samples_events_InsertCompleteEvent_data = data;
}

_ = pur_gwtplatform_samples_events_InsertCompleteEvent_InsertCompleteEvent__Lpur_gwtplatform_samples_model_Data_2V.prototype = pur_gwtplatform_samples_events_InsertCompleteEvent.prototype;
_.dispatch__Lcom_google_gwt_event_shared_EventHandler_2V = function pur_gwtplatform_samples_events_InsertCompleteEvent_dispatch__Lcom_google_gwt_event_shared_EventHandler_2V(handler){
  pur_gwtplatform_samples_events_InsertCompleteEvent_$dispatch__Lpur_gwtplatform_samples_events_InsertCompleteEvent_2Lpur_gwtplatform_samples_events_InsertCompleteEvent$InsertCompleteHandler_2V(this, com_google_gwt_lang_Cast_dynamicCast__Ljava_lang_Object_2ILjava_lang_Object_2(handler, Q$pur_gwtplatform_samples_events_InsertCompleteEvent$InsertCompleteHandler));
}
;
_.getAssociatedType__Lcom_google_gwt_event_shared_GwtEvent$Type_2 = function pur_gwtplatform_samples_events_InsertCompleteEvent_getAssociatedType__Lcom_google_gwt_event_shared_GwtEvent$Type_2(){
  return pur_gwtplatform_samples_events_InsertCompleteEvent_TYPE;
}
;
function pur_gwtplatform_samples_modules_IGinjectorImpl_$com$gwtplatform$mvp$client$HandlerContainerImpl_1automaticBind_1methodInjection__Lpur_gwtplatform_samples_modules_IGinjectorImpl_2Lcom_gwtplatform_mvp_client_HandlerContainerImpl_2Lcom_gwtplatform_mvp_client_AutobindDisable_2V(injectee, _0){
  injectee.automaticBind__Lcom_gwtplatform_mvp_client_AutobindDisable_2V(_0);
}

function pur_gwtplatform_samples_modules_IGinjectorImpl_$get_1Key$type$pur$gwtplatform$samples$presenter$MessageInsertPresenter$_1annotation$$none$$__Lpur_gwtplatform_samples_modules_IGinjectorImpl_2Lpur_gwtplatform_samples_presenter_MessageInsertPresenter_2(this$static){
  var pur_gwtplatform_samples_modules_IGinjectorImpl_$create_1Key$type$pur$gwtplatform$samples$presenter$MessageInsertPresenter$_1annotation$$none$$__Lpur_gwtplatform_samples_modules_IGinjectorImpl_2Lpur_gwtplatform_samples_presenter_MessageInsertPresenter_2_result_0;
  !this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$pur$gwtplatform$samples$presenter$MessageInsertPresenter$_1annotation$$none$$ && (this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$pur$gwtplatform$samples$presenter$MessageInsertPresenter$_1annotation$$none$$ = (pur_gwtplatform_samples_modules_IGinjectorImpl_$create_1Key$type$pur$gwtplatform$samples$presenter$MessageInsertPresenter$_1annotation$$none$$__Lpur_gwtplatform_samples_modules_IGinjectorImpl_2Lpur_gwtplatform_samples_presenter_MessageInsertPresenter_2_result_0 = pur_gwtplatform_samples_modules_IGinjectorImpl_$pur$gwtplatform$samples$presenter$MessageInsertPresenter_1MessageInsertPresenter_1methodInjection__Lpur_gwtplatform_samples_modules_IGinjectorImpl_2Lcom_google_web_bindery_event_shared_EventBus_2Lpur_gwtplatform_samples_views_IMessageInsertView_2Lpur_gwtplatform_samples_presenter_MessageInsertPresenter$MyProxy_2Lcom_gwtplatform_mvp_client_proxy_PlaceManager_2Lcom_gwtplatform_dispatch_shared_DispatchAsync_2Lpur_gwtplatform_samples_presenter_MessageInsertPresenter_2((!this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$com$google$web$bindery$event$shared$EventBus$_1annotation$$none$$ && (this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$com$google$web$bindery$event$shared$EventBus$_1annotation$$none$$ = new com_google_web_bindery_event_shared_SimpleEventBus_SimpleEventBus__V) , this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$com$google$web$bindery$event$shared$EventBus$_1annotation$$none$$), (!this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$pur$gwtplatform$samples$views$MessageInsertView$_1annotation$$none$$ && (this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$pur$gwtplatform$samples$views$MessageInsertView$_1annotation$$none$$ = new pur_gwtplatform_samples_views_MessageInsertView_MessageInsertView__Lpur_gwtplatform_samples_views_MessageInsertView$Binder_2V(new pur_gwtplatform_samples_views_MessageInsertView_1BinderImpl_MessageInsertView_1BinderImpl__V)) , this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$pur$gwtplatform$samples$views$MessageInsertView$_1annotation$$none$$), (!this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$pur$gwtplatform$samples$presenter$MessageInsertPresenter$MyProxy$_1annotation$$none$$ && (this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$pur$gwtplatform$samples$presenter$MessageInsertPresenter$MyProxy$_1annotation$$none$$ = new pur_gwtplatform_samples_presenter_MessageInsertPresenterMyProxyImpl_MessageInsertPresenterMyProxyImpl__V) , !this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$com$gwtplatform$mvp$client$proxy$PlaceManager$_1annotation$$none$$ && (this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$com$gwtplatform$mvp$client$proxy$PlaceManager$_1annotation$$none$$ = pur_gwtplatform_samples_modules_IGinjectorImpl_$create_1Key$type$pur$gwtplatform$samples$modules$PlaceManager$_1annotation$$none$$__Lpur_gwtplatform_samples_modules_IGinjectorImpl_2Lpur_gwtplatform_samples_modules_PlaceManager_2(this$static)) , this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$com$gwtplatform$mvp$client$proxy$PlaceManager$_1annotation$$none$$), !this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$com$gwtplatform$dispatch$shared$DispatchAsync$_1annotation$$none$$ && (this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$com$gwtplatform$dispatch$shared$DispatchAsync$_1annotation$$none$$ = pur_gwtplatform_samples_modules_IGinjectorImpl_$com$gwtplatform$dispatch$client$gin$DispatchAsyncModule_1provideDispatchAsync_1methodInjection__Lpur_gwtplatform_samples_modules_IGinjectorImpl_2Lcom_gwtplatform_dispatch_client_gin_DispatchAsyncModule_2Lcom_gwtplatform_dispatch_client_ExceptionHandler_2Lcom_gwtplatform_dispatch_shared_SecurityCookieAccessor_2Lcom_gwtplatform_dispatch_client_actionhandler_ClientActionHandlerRegistry_2Lcom_gwtplatform_dispatch_shared_DispatchAsync_2(new com_gwtplatform_dispatch_client_gin_DispatchAsyncModule_DispatchAsyncModule__V, new com_gwtplatform_dispatch_client_DefaultExceptionHandler_DefaultExceptionHandler__V, new com_gwtplatform_dispatch_client_DefaultSecurityCookieAccessor_DefaultSecurityCookieAccessor__V, (!this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$com$gwtplatform$dispatch$client$actionhandler$ClientActionHandlerRegistry$_1annotation$$none$$ && (this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$com$gwtplatform$dispatch$client$actionhandler$ClientActionHandlerRegistry$_1annotation$$none$$ = new com_gwtplatform_dispatch_client_actionhandler_DefaultClientActionHandlerRegistry_DefaultClientActionHandlerRegistry__V) , this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$com$gwtplatform$dispatch$client$actionhandler$ClientActionHandlerRegistry$_1annotation$$none$$)))) , pur_gwtplatform_samples_modules_IGinjectorImpl_$com$gwtplatform$mvp$client$HandlerContainerImpl_1automaticBind_1methodInjection__Lpur_gwtplatform_samples_modules_IGinjectorImpl_2Lcom_gwtplatform_mvp_client_HandlerContainerImpl_2Lcom_gwtplatform_mvp_client_AutobindDisable_2V(pur_gwtplatform_samples_modules_IGinjectorImpl_$create_1Key$type$pur$gwtplatform$samples$presenter$MessageInsertPresenter$_1annotation$$none$$__Lpur_gwtplatform_samples_modules_IGinjectorImpl_2Lpur_gwtplatform_samples_presenter_MessageInsertPresenter_2_result_0, (!this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$com$gwtplatform$mvp$client$AutobindDisable$_1annotation$$none$$ && (this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$com$gwtplatform$mvp$client$AutobindDisable$_1annotation$$none$$ = new com_gwtplatform_mvp_client_AutobindDisable_AutobindDisable__V) , this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$com$gwtplatform$mvp$client$AutobindDisable$_1annotation$$none$$)) , pur_gwtplatform_samples_modules_IGinjectorImpl_$create_1Key$type$pur$gwtplatform$samples$presenter$MessageInsertPresenter$_1annotation$$none$$__Lpur_gwtplatform_samples_modules_IGinjectorImpl_2Lpur_gwtplatform_samples_presenter_MessageInsertPresenter_2_result_0));
  return this$static.pur_gwtplatform_samples_modules_IGinjectorImpl_singleton_1Key$type$pur$gwtplatform$samples$presenter$MessageInsertPresenter$_1annotation$$none$$;
}

function pur_gwtplatform_samples_modules_IGinjectorImpl_$pur$gwtplatform$samples$presenter$MessageInsertPresenter_1MessageInsertPresenter_1methodInjection__Lpur_gwtplatform_samples_modules_IGinjectorImpl_2Lcom_google_web_bindery_event_shared_EventBus_2Lpur_gwtplatform_samples_views_IMessageInsertView_2Lpur_gwtplatform_samples_presenter_MessageInsertPresenter$MyProxy_2Lcom_gwtplatform_mvp_client_proxy_PlaceManager_2Lcom_gwtplatform_dispatch_shared_DispatchAsync_2Lpur_gwtplatform_samples_presenter_MessageInsertPresenter_2(_0, _1, _3){
  return new pur_gwtplatform_samples_presenter_MessageInsertPresenter_MessageInsertPresenter__Lcom_google_web_bindery_event_shared_EventBus_2Lpur_gwtplatform_samples_views_IMessageInsertView_2Lpur_gwtplatform_samples_presenter_MessageInsertPresenter$MyProxy_2Lcom_gwtplatform_mvp_client_proxy_PlaceManager_2Lcom_gwtplatform_dispatch_shared_DispatchAsync_2V(_0, _1, _3);
}

_ = pur_gwtplatform_samples_modules_IGinjectorImpl$1$1.prototype;
_.onSuccess__V = function pur_gwtplatform_samples_modules_IGinjectorImpl$1$1_onSuccess__V(){
  com_gwtplatform_mvp_client_proxy_NotifyingAsyncCallback_$onSuccess__Lcom_gwtplatform_mvp_client_proxy_NotifyingAsyncCallback_2Ljava_lang_Object_2V(this.pur_gwtplatform_samples_modules_IGinjectorImpl$1$1_val$callback, pur_gwtplatform_samples_modules_IGinjectorImpl_$get_1Key$type$pur$gwtplatform$samples$presenter$MessageInsertPresenter$_1annotation$$none$$__Lpur_gwtplatform_samples_modules_IGinjectorImpl_2Lpur_gwtplatform_samples_presenter_MessageInsertPresenter_2(this.pur_gwtplatform_samples_modules_IGinjectorImpl$1$1_this$1.pur_gwtplatform_samples_modules_IGinjectorImpl$1_this$0));
}
;
function pur_gwtplatform_samples_presenter_MessageInsertPresenter_MessageInsertPresenter__Lcom_google_web_bindery_event_shared_EventBus_2Lpur_gwtplatform_samples_views_IMessageInsertView_2Lpur_gwtplatform_samples_presenter_MessageInsertPresenter$MyProxy_2Lcom_gwtplatform_mvp_client_proxy_PlaceManager_2Lcom_gwtplatform_dispatch_shared_DispatchAsync_2V(eventBus, view, placeManager){
  com_gwtplatform_mvp_client_PresenterWidget_PresenterWidget__Lcom_google_web_bindery_event_shared_EventBus_2Lcom_gwtplatform_mvp_client_View_2V.call(this, eventBus, view);
  this.pur_gwtplatform_samples_presenter_MessageInsertPresenter_eventBus = eventBus;
  this.pur_gwtplatform_samples_presenter_MessageInsertPresenter_placeManager = placeManager;
}

_ = pur_gwtplatform_samples_presenter_MessageInsertPresenter_MessageInsertPresenter__Lcom_google_web_bindery_event_shared_EventBus_2Lpur_gwtplatform_samples_views_IMessageInsertView_2Lpur_gwtplatform_samples_presenter_MessageInsertPresenter$MyProxy_2Lcom_gwtplatform_mvp_client_proxy_PlaceManager_2Lcom_gwtplatform_dispatch_shared_DispatchAsync_2V.prototype = pur_gwtplatform_samples_presenter_MessageInsertPresenter.prototype;
_.onBind__V = function pur_gwtplatform_samples_presenter_MessageInsertPresenter_onBind__V(){
  com_gwtplatform_mvp_client_HandlerContainerImpl_$registerHandler__Lcom_gwtplatform_mvp_client_HandlerContainerImpl_2Lcom_google_web_bindery_event_shared_HandlerRegistration_2V(this, com_google_gwt_user_client_ui_Widget_$addDomHandler__Lcom_google_gwt_user_client_ui_Widget_2Lcom_google_gwt_event_shared_EventHandler_2Lcom_google_gwt_event_dom_client_DomEvent$Type_2Lcom_google_gwt_event_shared_HandlerRegistration_2(com_google_gwt_lang_Cast_dynamicCast__Ljava_lang_Object_2ILjava_lang_Object_2(com_google_gwt_lang_Cast_dynamicCast__Ljava_lang_Object_2ILjava_lang_Object_2(this.com_gwtplatform_mvp_client_PresenterWidget_view, Q$pur_gwtplatform_samples_views_IMessageInsertView), Q$pur_gwtplatform_samples_views_MessageInsertView).pur_gwtplatform_samples_views_MessageInsertView_insertButton, new pur_gwtplatform_samples_presenter_MessageInsertPresenter$1_MessageInsertPresenter$1__Lpur_gwtplatform_samples_presenter_MessageInsertPresenter_2V(this), (com_google_gwt_event_dom_client_ClickEvent_$clinit__V() , com_google_gwt_event_dom_client_ClickEvent_$clinit__V() , com_google_gwt_event_dom_client_ClickEvent_TYPE)));
  com_gwtplatform_mvp_client_HandlerContainerImpl_$registerHandler__Lcom_gwtplatform_mvp_client_HandlerContainerImpl_2Lcom_google_web_bindery_event_shared_HandlerRegistration_2V(this, com_google_gwt_user_client_ui_Widget_$addDomHandler__Lcom_google_gwt_user_client_ui_Widget_2Lcom_google_gwt_event_shared_EventHandler_2Lcom_google_gwt_event_dom_client_DomEvent$Type_2Lcom_google_gwt_event_shared_HandlerRegistration_2(com_google_gwt_lang_Cast_dynamicCast__Ljava_lang_Object_2ILjava_lang_Object_2(com_google_gwt_lang_Cast_dynamicCast__Ljava_lang_Object_2ILjava_lang_Object_2(this.com_gwtplatform_mvp_client_PresenterWidget_view, Q$pur_gwtplatform_samples_views_IMessageInsertView), Q$pur_gwtplatform_samples_views_MessageInsertView).pur_gwtplatform_samples_views_MessageInsertView_cancelButton, new pur_gwtplatform_samples_presenter_MessageInsertPresenter$2_MessageInsertPresenter$2__Lpur_gwtplatform_samples_presenter_MessageInsertPresenter_2V(this), com_google_gwt_event_dom_client_ClickEvent_TYPE));
}
;
_.onReveal__V = function pur_gwtplatform_samples_presenter_MessageInsertPresenter_onReveal__V(){
}
;
_.revealInParent__V = function pur_gwtplatform_samples_presenter_MessageInsertPresenter_revealInParent__V(){
  com_gwtplatform_mvp_client_proxy_RevealRootContentEvent_$clinit__V();
  com_gwtplatform_mvp_client_PresenterWidget_$fireEvent__Lcom_gwtplatform_mvp_client_PresenterWidget_2Lcom_google_gwt_event_shared_GwtEvent_2V(this, new com_gwtplatform_mvp_client_proxy_RevealRootContentEvent_RevealRootContentEvent__Lcom_gwtplatform_mvp_client_Presenter_2V(this));
}
;
function pur_gwtplatform_samples_presenter_MessageInsertPresenter$1_MessageInsertPresenter$1__Lpur_gwtplatform_samples_presenter_MessageInsertPresenter_2V(this$0){
  this.pur_gwtplatform_samples_presenter_MessageInsertPresenter$1_this$0 = this$0;
}

_ = pur_gwtplatform_samples_presenter_MessageInsertPresenter$1_MessageInsertPresenter$1__Lpur_gwtplatform_samples_presenter_MessageInsertPresenter_2V.prototype = pur_gwtplatform_samples_presenter_MessageInsertPresenter$1.prototype;
_.onClick__Lcom_google_gwt_event_dom_client_ClickEvent_2V = function pur_gwtplatform_samples_presenter_MessageInsertPresenter$1_onClick__Lcom_google_gwt_event_dom_client_ClickEvent_2V(event){
  var data, key, stockstore;
  key = com_google_gwt_dom_client_Element_$getPropertyString__Lcom_google_gwt_dom_client_Element_2Ljava_lang_String_2Ljava_lang_String_2(com_google_gwt_lang_Cast_dynamicCast__Ljava_lang_Object_2ILjava_lang_Object_2(com_google_gwt_lang_Cast_dynamicCast__Ljava_lang_Object_2ILjava_lang_Object_2(this.pur_gwtplatform_samples_presenter_MessageInsertPresenter$1_this$0.com_gwtplatform_mvp_client_PresenterWidget_view, Q$pur_gwtplatform_samples_views_IMessageInsertView), Q$pur_gwtplatform_samples_views_MessageInsertView).pur_gwtplatform_samples_views_MessageInsertView_keyStock.com_google_gwt_user_client_ui_UIObject_element, $intern_51);
  data = com_google_gwt_dom_client_Element_$getPropertyString__Lcom_google_gwt_dom_client_Element_2Ljava_lang_String_2Ljava_lang_String_2(com_google_gwt_lang_Cast_dynamicCast__Ljava_lang_Object_2ILjava_lang_Object_2(com_google_gwt_lang_Cast_dynamicCast__Ljava_lang_Object_2ILjava_lang_Object_2(this.pur_gwtplatform_samples_presenter_MessageInsertPresenter$1_this$0.com_gwtplatform_mvp_client_PresenterWidget_view, Q$pur_gwtplatform_samples_views_IMessageInsertView), Q$pur_gwtplatform_samples_views_MessageInsertView).pur_gwtplatform_samples_views_MessageInsertView_dataStock.com_google_gwt_user_client_ui_UIObject_element, $intern_51);
  stockstore = com_google_gwt_storage_client_Storage_getLocalStorageIfSupported__Lcom_google_gwt_storage_client_Storage_2();
  !!stockstore && com_google_gwt_storage_client_StorageImplNonNativeEvents_$setItem__Lcom_google_gwt_storage_client_StorageImplNonNativeEvents_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2V(stockstore.com_google_gwt_storage_client_Storage_storage, key, data);
  com_google_web_bindery_event_shared_SimpleEventBus_$doFire__Lcom_google_web_bindery_event_shared_SimpleEventBus_2Lcom_google_web_bindery_event_shared_Event_2Ljava_lang_Object_2V(this.pur_gwtplatform_samples_presenter_MessageInsertPresenter$1_this$0.pur_gwtplatform_samples_presenter_MessageInsertPresenter_eventBus, new pur_gwtplatform_samples_events_InsertCompleteEvent_InsertCompleteEvent__Lpur_gwtplatform_samples_model_Data_2V(new pur_gwtplatform_samples_model_Data_Data__Ljava_lang_String_2Ljava_lang_String_2V(key, data)), null);
  com_gwtplatform_mvp_client_proxy_PlaceManagerImpl_$revealPlace__Lcom_gwtplatform_mvp_client_proxy_PlaceManagerImpl_2Lcom_gwtplatform_mvp_client_proxy_PlaceRequest_2ZV(this.pur_gwtplatform_samples_presenter_MessageInsertPresenter$1_this$0.pur_gwtplatform_samples_presenter_MessageInsertPresenter_placeManager, new com_gwtplatform_mvp_client_proxy_PlaceRequest_PlaceRequest__Ljava_lang_String_2V($intern_37), true);
}
;
function pur_gwtplatform_samples_presenter_MessageInsertPresenter$2_MessageInsertPresenter$2__Lpur_gwtplatform_samples_presenter_MessageInsertPresenter_2V(this$0){
  this.pur_gwtplatform_samples_presenter_MessageInsertPresenter$2_this$0 = this$0;
}

_ = pur_gwtplatform_samples_presenter_MessageInsertPresenter$2_MessageInsertPresenter$2__Lpur_gwtplatform_samples_presenter_MessageInsertPresenter_2V.prototype = pur_gwtplatform_samples_presenter_MessageInsertPresenter$2.prototype;
_.onClick__Lcom_google_gwt_event_dom_client_ClickEvent_2V = function pur_gwtplatform_samples_presenter_MessageInsertPresenter$2_onClick__Lcom_google_gwt_event_dom_client_ClickEvent_2V(event){
  com_google_gwt_lang_Cast_dynamicCast__Ljava_lang_Object_2ILjava_lang_Object_2(com_google_gwt_lang_Cast_dynamicCast__Ljava_lang_Object_2ILjava_lang_Object_2(this.pur_gwtplatform_samples_presenter_MessageInsertPresenter$2_this$0.com_gwtplatform_mvp_client_PresenterWidget_view, Q$pur_gwtplatform_samples_views_IMessageInsertView), Q$pur_gwtplatform_samples_views_MessageInsertView).pur_gwtplatform_samples_views_MessageInsertView_keyStock.com_google_gwt_user_client_ui_UIObject_element[$intern_51] = $intern_7;
  com_google_gwt_lang_Cast_dynamicCast__Ljava_lang_Object_2ILjava_lang_Object_2(com_google_gwt_lang_Cast_dynamicCast__Ljava_lang_Object_2ILjava_lang_Object_2(this.pur_gwtplatform_samples_presenter_MessageInsertPresenter$2_this$0.com_gwtplatform_mvp_client_PresenterWidget_view, Q$pur_gwtplatform_samples_views_IMessageInsertView), Q$pur_gwtplatform_samples_views_MessageInsertView).pur_gwtplatform_samples_views_MessageInsertView_dataStock.com_google_gwt_user_client_ui_UIObject_element[$intern_51] = $intern_7;
  com_gwtplatform_mvp_client_proxy_PlaceManagerImpl_$revealPlace__Lcom_gwtplatform_mvp_client_proxy_PlaceManagerImpl_2Lcom_gwtplatform_mvp_client_proxy_PlaceRequest_2ZV(this.pur_gwtplatform_samples_presenter_MessageInsertPresenter$2_this$0.pur_gwtplatform_samples_presenter_MessageInsertPresenter_placeManager, new com_gwtplatform_mvp_client_proxy_PlaceRequest_PlaceRequest__Ljava_lang_String_2V($intern_37), true);
}
;
function pur_gwtplatform_samples_views_MessageInsertView_MessageInsertView__Lpur_gwtplatform_samples_views_MessageInsertView$Binder_2V(){
  this.pur_gwtplatform_samples_views_MessageInsertView_widget = pur_gwtplatform_samples_views_MessageInsertView_1BinderImpl_$createAndBindUi__Lpur_gwtplatform_samples_views_MessageInsertView_1BinderImpl_2Lpur_gwtplatform_samples_views_MessageInsertView_2Lcom_google_gwt_user_client_ui_Widget_2(this);
}

_ = pur_gwtplatform_samples_views_MessageInsertView_MessageInsertView__Lpur_gwtplatform_samples_views_MessageInsertView$Binder_2V.prototype = pur_gwtplatform_samples_views_MessageInsertView.prototype;
_.asWidget__Lcom_google_gwt_user_client_ui_Widget_2 = function pur_gwtplatform_samples_views_MessageInsertView_asWidget__Lcom_google_gwt_user_client_ui_Widget_2(){
  return this.pur_gwtplatform_samples_views_MessageInsertView_widget;
}
;
function pur_gwtplatform_samples_views_MessageInsertView_1BinderImpl_$createAndBindUi__Lpur_gwtplatform_samples_views_MessageInsertView_1BinderImpl_2Lpur_gwtplatform_samples_views_MessageInsertView_2Lcom_google_gwt_user_client_ui_Widget_2(owner){
  var attachRecord0, cancelButton, dataStock, domId0, domId0Element, f_HTMLPanel1, f_HorizontalPanel10, f_HorizontalPanel4, f_HorizontalPanel6, f_HorizontalPanel8, f_Label5, f_Label7, f_Label9, f_LayoutPanel2, f_VerticalPanel3, insertButton, keyStock, pur_gwtplatform_samples_views_MessageInsertView_1BinderImpl_1TemplateImpl_$html1__Lpur_gwtplatform_samples_views_MessageInsertView_1BinderImpl_1TemplateImpl_2Ljava_lang_String_2Lcom_google_gwt_safehtml_shared_SafeHtml_2_sb_0;
  domId0 = com_google_gwt_dom_client_Document_$createUniqueId__Lcom_google_gwt_dom_client_Document_2Ljava_lang_String_2($doc);
  f_Label5 = new com_google_gwt_user_client_ui_Label_Label__V;
  f_HorizontalPanel4 = new com_google_gwt_user_client_ui_HorizontalPanel_HorizontalPanel__V;
  f_Label7 = new com_google_gwt_user_client_ui_Label_Label__V;
  keyStock = new com_google_gwt_user_client_ui_TextBox_TextBox__V;
  f_HorizontalPanel6 = new com_google_gwt_user_client_ui_HorizontalPanel_HorizontalPanel__V;
  f_Label9 = new com_google_gwt_user_client_ui_Label_Label__V;
  dataStock = new com_google_gwt_user_client_ui_TextBox_TextBox__V;
  f_HorizontalPanel8 = new com_google_gwt_user_client_ui_HorizontalPanel_HorizontalPanel__V;
  insertButton = new com_google_gwt_user_client_ui_Button_Button__V;
  cancelButton = new com_google_gwt_user_client_ui_Button_Button__V;
  f_HorizontalPanel10 = new com_google_gwt_user_client_ui_HorizontalPanel_HorizontalPanel__V;
  f_VerticalPanel3 = new com_google_gwt_user_client_ui_VerticalPanel_VerticalPanel__V;
  f_LayoutPanel2 = new com_google_gwt_user_client_ui_LayoutPanel_LayoutPanel__V;
  f_HTMLPanel1 = new com_google_gwt_user_client_ui_HTMLPanel_HTMLPanel__Ljava_lang_String_2V((pur_gwtplatform_samples_views_MessageInsertView_1BinderImpl_1TemplateImpl_$html1__Lpur_gwtplatform_samples_views_MessageInsertView_1BinderImpl_1TemplateImpl_2Ljava_lang_String_2Lcom_google_gwt_safehtml_shared_SafeHtml_2_sb_0 = new java_lang_StringBuilder_StringBuilder__V , pur_gwtplatform_samples_views_MessageInsertView_1BinderImpl_1TemplateImpl_$html1__Lpur_gwtplatform_samples_views_MessageInsertView_1BinderImpl_1TemplateImpl_2Ljava_lang_String_2Lcom_google_gwt_safehtml_shared_SafeHtml_2_sb_0.java_lang_StringBuilder_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string += $intern_52 , java_lang_StringBuilder_$append__Ljava_lang_StringBuilder_2Ljava_lang_String_2Ljava_lang_StringBuilder_2(pur_gwtplatform_samples_views_MessageInsertView_1BinderImpl_1TemplateImpl_$html1__Lpur_gwtplatform_samples_views_MessageInsertView_1BinderImpl_1TemplateImpl_2Ljava_lang_String_2Lcom_google_gwt_safehtml_shared_SafeHtml_2_sb_0, com_google_gwt_safehtml_shared_SafeHtmlUtils_htmlEscape__Ljava_lang_String_2Ljava_lang_String_2(domId0)) , pur_gwtplatform_samples_views_MessageInsertView_1BinderImpl_1TemplateImpl_$html1__Lpur_gwtplatform_samples_views_MessageInsertView_1BinderImpl_1TemplateImpl_2Ljava_lang_String_2Lcom_google_gwt_safehtml_shared_SafeHtml_2_sb_0.java_lang_StringBuilder_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string += $intern_53 , new com_google_gwt_safehtml_shared_OnlyToBeUsedInGeneratedCodeStringBlessedAsSafeHtml_OnlyToBeUsedInGeneratedCodeStringBlessedAsSafeHtml__Ljava_lang_String_2V(pur_gwtplatform_samples_views_MessageInsertView_1BinderImpl_1TemplateImpl_$html1__Lpur_gwtplatform_samples_views_MessageInsertView_1BinderImpl_1TemplateImpl_2Ljava_lang_String_2Lcom_google_gwt_safehtml_shared_SafeHtml_2_sb_0.java_lang_StringBuilder_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string)).com_google_gwt_safehtml_shared_OnlyToBeUsedInGeneratedCodeStringBlessedAsSafeHtml_html);
  com_google_gwt_user_client_ui_VerticalPanel_$setHorizontalAlignment__Lcom_google_gwt_user_client_ui_VerticalPanel_2Lcom_google_gwt_user_client_ui_HasHorizontalAlignment$HorizontalAlignmentConstant_2V(f_VerticalPanel3, (com_google_gwt_user_client_ui_HasHorizontalAlignment_$clinit__V() , com_google_gwt_user_client_ui_HasHorizontalAlignment_ALIGN_1CENTER));
  com_google_gwt_user_client_ui_HorizontalPanel_$setHorizontalAlignment__Lcom_google_gwt_user_client_ui_HorizontalPanel_2Lcom_google_gwt_user_client_ui_HasHorizontalAlignment$HorizontalAlignmentConstant_2V(f_HorizontalPanel4, com_google_gwt_user_client_ui_HasHorizontalAlignment_ALIGN_1CENTER);
  com_google_gwt_user_client_ui_LabelBase_$setHorizontalAlignment__Lcom_google_gwt_user_client_ui_LabelBase_2Lcom_google_gwt_user_client_ui_HasHorizontalAlignment$HorizontalAlignmentConstant_2V(f_Label5, com_google_gwt_user_client_ui_HasHorizontalAlignment_ALIGN_1CENTER);
  com_google_gwt_user_client_ui_DirectionalTextHelper_$setTextOrHtml__Lcom_google_gwt_user_client_ui_DirectionalTextHelper_2Ljava_lang_String_2ZV(f_Label5.com_google_gwt_user_client_ui_LabelBase_directionalTextHelper, 'Saisir des donn\xE9es dans le LocalStorage');
  com_google_gwt_user_client_ui_LabelBase_$updateHorizontalAlignment__Lcom_google_gwt_user_client_ui_LabelBase_2V(f_Label5);
  f_Label5.com_google_gwt_user_client_ui_UIObject_element.style[$intern_54] = '460';
  com_google_gwt_user_client_ui_HorizontalPanel_$add__Lcom_google_gwt_user_client_ui_HorizontalPanel_2Lcom_google_gwt_user_client_ui_Widget_2V(f_HorizontalPanel4, f_Label5);
  f_HorizontalPanel4.com_google_gwt_user_client_ui_UIObject_element[$intern_55] = 'gwt-StackPanel';
  f_HorizontalPanel4.com_google_gwt_user_client_ui_UIObject_element.style[$intern_54] = $intern_56;
  com_google_gwt_user_client_ui_VerticalPanel_$add__Lcom_google_gwt_user_client_ui_VerticalPanel_2Lcom_google_gwt_user_client_ui_Widget_2V(f_VerticalPanel3, f_HorizontalPanel4);
  com_google_gwt_user_client_ui_LabelBase_$setHorizontalAlignment__Lcom_google_gwt_user_client_ui_LabelBase_2Lcom_google_gwt_user_client_ui_HasHorizontalAlignment$HorizontalAlignmentConstant_2V(f_Label7, com_google_gwt_user_client_ui_HasHorizontalAlignment_ALIGN_1RIGHT);
  com_google_gwt_user_client_ui_DirectionalTextHelper_$setTextOrHtml__Lcom_google_gwt_user_client_ui_DirectionalTextHelper_2Ljava_lang_String_2ZV(f_Label7.com_google_gwt_user_client_ui_LabelBase_directionalTextHelper, 'Cl\xE9 de stockage');
  com_google_gwt_user_client_ui_LabelBase_$updateHorizontalAlignment__Lcom_google_gwt_user_client_ui_LabelBase_2V(f_Label7);
  f_Label7.com_google_gwt_user_client_ui_UIObject_element.style[$intern_54] = $intern_57;
  com_google_gwt_user_client_ui_HorizontalPanel_$add__Lcom_google_gwt_user_client_ui_HorizontalPanel_2Lcom_google_gwt_user_client_ui_Widget_2V(f_HorizontalPanel6, f_Label7);
  com_google_gwt_user_client_ui_HorizontalPanel_$add__Lcom_google_gwt_user_client_ui_HorizontalPanel_2Lcom_google_gwt_user_client_ui_Widget_2V(f_HorizontalPanel6, keyStock);
  f_HorizontalPanel6.com_google_gwt_user_client_ui_UIObject_element.style[$intern_54] = $intern_56;
  f_HorizontalPanel6.com_google_gwt_user_client_ui_CellPanel_table[$intern_48] = 3;
  com_google_gwt_user_client_ui_VerticalPanel_$add__Lcom_google_gwt_user_client_ui_VerticalPanel_2Lcom_google_gwt_user_client_ui_Widget_2V(f_VerticalPanel3, f_HorizontalPanel6);
  com_google_gwt_user_client_ui_LabelBase_$setHorizontalAlignment__Lcom_google_gwt_user_client_ui_LabelBase_2Lcom_google_gwt_user_client_ui_HasHorizontalAlignment$HorizontalAlignmentConstant_2V(f_Label9, com_google_gwt_user_client_ui_HasHorizontalAlignment_ALIGN_1RIGHT);
  com_google_gwt_user_client_ui_DirectionalTextHelper_$setTextOrHtml__Lcom_google_gwt_user_client_ui_DirectionalTextHelper_2Ljava_lang_String_2ZV(f_Label9.com_google_gwt_user_client_ui_LabelBase_directionalTextHelper, 'Donn\xE9e \xE0 stoquer');
  com_google_gwt_user_client_ui_LabelBase_$updateHorizontalAlignment__Lcom_google_gwt_user_client_ui_LabelBase_2V(f_Label9);
  f_Label9.com_google_gwt_user_client_ui_UIObject_element.style[$intern_54] = $intern_57;
  com_google_gwt_user_client_ui_HorizontalPanel_$add__Lcom_google_gwt_user_client_ui_HorizontalPanel_2Lcom_google_gwt_user_client_ui_Widget_2V(f_HorizontalPanel8, f_Label9);
  com_google_gwt_user_client_ui_HorizontalPanel_$add__Lcom_google_gwt_user_client_ui_HorizontalPanel_2Lcom_google_gwt_user_client_ui_Widget_2V(f_HorizontalPanel8, dataStock);
  f_HorizontalPanel8.com_google_gwt_user_client_ui_UIObject_element.style[$intern_54] = $intern_56;
  f_HorizontalPanel8.com_google_gwt_user_client_ui_CellPanel_table[$intern_48] = 3;
  com_google_gwt_user_client_ui_VerticalPanel_$add__Lcom_google_gwt_user_client_ui_VerticalPanel_2Lcom_google_gwt_user_client_ui_Widget_2V(f_VerticalPanel3, f_HorizontalPanel8);
  com_google_gwt_dom_client_DOMImplStandard_$setInnerText__Lcom_google_gwt_dom_client_DOMImplStandard_2Lcom_google_gwt_dom_client_Element_2Ljava_lang_String_2V(insertButton.com_google_gwt_user_client_ui_UIObject_element, $intern_58);
  insertButton.com_google_gwt_user_client_ui_UIObject_element.style[$intern_54] = $intern_59;
  com_google_gwt_user_client_ui_HorizontalPanel_$add__Lcom_google_gwt_user_client_ui_HorizontalPanel_2Lcom_google_gwt_user_client_ui_Widget_2V(f_HorizontalPanel10, insertButton);
  com_google_gwt_dom_client_DOMImplStandard_$setInnerText__Lcom_google_gwt_dom_client_DOMImplStandard_2Lcom_google_gwt_dom_client_Element_2Ljava_lang_String_2V(cancelButton.com_google_gwt_user_client_ui_UIObject_element, 'Annuler');
  cancelButton.com_google_gwt_user_client_ui_UIObject_element.style[$intern_54] = $intern_59;
  com_google_gwt_user_client_ui_HorizontalPanel_$add__Lcom_google_gwt_user_client_ui_HorizontalPanel_2Lcom_google_gwt_user_client_ui_Widget_2V(f_HorizontalPanel10, cancelButton);
  f_HorizontalPanel10.com_google_gwt_user_client_ui_UIObject_element.style[$intern_54] = $intern_56;
  f_HorizontalPanel10.com_google_gwt_user_client_ui_CellPanel_table[$intern_48] = 10;
  com_google_gwt_user_client_ui_VerticalPanel_$add__Lcom_google_gwt_user_client_ui_VerticalPanel_2Lcom_google_gwt_user_client_ui_Widget_2V(f_VerticalPanel3, f_HorizontalPanel10);
  f_VerticalPanel3.com_google_gwt_user_client_ui_CellPanel_table[$intern_60] = $intern_61;
  f_VerticalPanel3.com_google_gwt_user_client_ui_UIObject_element.style[$intern_54] = '500px';
  com_google_gwt_user_client_ui_LayoutPanel_$insert__Lcom_google_gwt_user_client_ui_LayoutPanel_2Lcom_google_gwt_user_client_ui_Widget_2IV(f_LayoutPanel2, f_VerticalPanel3, f_LayoutPanel2.com_google_gwt_user_client_ui_ComplexPanel_children.com_google_gwt_user_client_ui_WidgetCollection_size);
  com_google_gwt_user_client_ui_LayoutPanel_$setWidgetLeftWidth__Lcom_google_gwt_user_client_ui_LayoutPanel_2Lcom_google_gwt_user_client_ui_Widget_2DLcom_google_gwt_dom_client_Style$Unit_2DLcom_google_gwt_dom_client_Style$Unit_2V(f_LayoutPanel2, f_VerticalPanel3, 153, (com_google_gwt_dom_client_Style$Unit_$clinit__V() , com_google_gwt_dom_client_Style$Unit_PX), 500, com_google_gwt_dom_client_Style$Unit_PX);
  com_google_gwt_user_client_ui_LayoutPanel_$setWidgetTopHeight__Lcom_google_gwt_user_client_ui_LayoutPanel_2Lcom_google_gwt_user_client_ui_Widget_2DLcom_google_gwt_dom_client_Style$Unit_2DLcom_google_gwt_dom_client_Style$Unit_2V(f_LayoutPanel2, f_VerticalPanel3, 29, com_google_gwt_dom_client_Style$Unit_PX, 196, com_google_gwt_dom_client_Style$Unit_PX);
  f_LayoutPanel2.com_google_gwt_user_client_ui_UIObject_element.style[$intern_62] = '194px';
  f_LayoutPanel2.com_google_gwt_user_client_ui_UIObject_element.style[$intern_54] = $intern_63;
  f_HTMLPanel1.com_google_gwt_user_client_ui_UIObject_element.style[$intern_62] = '199px';
  f_HTMLPanel1.com_google_gwt_user_client_ui_UIObject_element.style[$intern_54] = '750px';
  attachRecord0 = com_google_gwt_uibinder_client_UiBinderUtil_attachToDom__Lcom_google_gwt_dom_client_Element_2Lcom_google_gwt_uibinder_client_UiBinderUtil$TempAttachment_2(f_HTMLPanel1.com_google_gwt_user_client_ui_UIObject_element);
  domId0Element = com_google_gwt_dom_client_Document_$getElementById__Lcom_google_gwt_dom_client_Document_2Ljava_lang_String_2Lcom_google_gwt_dom_client_Element_2($doc, domId0);
  attachRecord0.com_google_gwt_uibinder_client_UiBinderUtil$TempAttachment_origParent?com_google_gwt_dom_client_Node_$insertBefore__Lcom_google_gwt_dom_client_Node_2Lcom_google_gwt_dom_client_Node_2Lcom_google_gwt_dom_client_Node_2Lcom_google_gwt_dom_client_Node_2(attachRecord0.com_google_gwt_uibinder_client_UiBinderUtil$TempAttachment_origParent, attachRecord0.com_google_gwt_uibinder_client_UiBinderUtil$TempAttachment_element, attachRecord0.com_google_gwt_uibinder_client_UiBinderUtil$TempAttachment_origSibling):com_google_gwt_uibinder_client_UiBinderUtil_orphan__Lcom_google_gwt_dom_client_Node_2V(attachRecord0.com_google_gwt_uibinder_client_UiBinderUtil$TempAttachment_element);
  com_google_gwt_user_client_ui_HTMLPanel_$addAndReplaceElement__Lcom_google_gwt_user_client_ui_HTMLPanel_2Lcom_google_gwt_user_client_ui_Widget_2Lcom_google_gwt_user_client_Element_2V(f_HTMLPanel1, f_LayoutPanel2, domId0Element);
  owner.pur_gwtplatform_samples_views_MessageInsertView_cancelButton = cancelButton;
  owner.pur_gwtplatform_samples_views_MessageInsertView_dataStock = dataStock;
  owner.pur_gwtplatform_samples_views_MessageInsertView_insertButton = insertButton;
  owner.pur_gwtplatform_samples_views_MessageInsertView_keyStock = keyStock;
  return f_HTMLPanel1;
}

function pur_gwtplatform_samples_views_MessageInsertView_1BinderImpl_MessageInsertView_1BinderImpl__V(){
}

_ = pur_gwtplatform_samples_views_MessageInsertView_1BinderImpl_MessageInsertView_1BinderImpl__V.prototype = pur_gwtplatform_samples_views_MessageInsertView_1BinderImpl.prototype;
$entry(com_google_gwt_core_client_impl_AsyncFragmentLoader_onLoad__IV)(1);
